In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [2]:
from retrieval.bm25_search import BM25SearchEngine

In [3]:
bm25 = BM25SearchEngine(top_k=10)

In [4]:
bm25.load_data("../data/processed/business_reviews_with_checkins.parquet")

✅ Loaded 150346 documents

In [5]:
bm25.build_index()

⚠️ Could not load BM25 index, rebuilding from scratch: [Errno 2] No such file or directory: '../models/bm25_tokenized_corpus.pkl'
✅ Loaded 150346 documents
✅ BM25 index built and saved.

In [6]:
results = bm25.search("best vegan pizza in Austin")

In [7]:
results

,name,city,categories,stars,review_count,bm25_score
88332,Tomatillo's,New Orleans,"Restaurants, Mexican, Latin American",3.0,6,26.237472
131245,Whole Foods Market,New Orleans,"Beer, Wine & Spirits, Specialty Food, Health M...",3.5,182,26.215044
98219,Tampa Pizza Company,Tampa,"Pizza, Restaurants, Vegetarian, Gluten-Free",4.0,289,26.077206
147865,Slice,Philadelphia,"Italian, Barbeque, Restaurants, Pizza",3.5,90,25.492165
140524,Whole Foods Market,Tucson,"Personal Shopping, Beauty & Spas, Grocery, Hea...",3.5,102,25.195955
80495,Jad's Pizza,Downingtown,"Burgers, Restaurants, Chicken Wings, Pizza",4.5,43,25.076595
139,Whole Foods Market,Carmel,"Food, Organic Stores, Specialty Food, Health M...",3.5,44,24.818498
79560,Ladybird Taco,Nashville,"Mexican, Tacos, Restaurants, Breakfast & Brunc...",4.5,93,24.817465
82353,G's Pizza,New Orleans,"Pizza, Restaurants, Food Delivery Services, Wi...",4.0,161,24.771169
133487,MOD Pizza,Ladue,"Fast Food, Restaurants, Pizza",4.0,89,24.464050

In [8]:
bm25.search("bread")

,name,city,categories,stars,review_count,bm25_score
137078,Barrio Bread,Tucson,"Food, Specialty Food, Bakeries, Restaurants",5.0,221,3.214610
130906,Faedo Family Bakery,Tampa,"Bakeries, Food, Restaurants",4.5,93,3.208491
72773,House of Bread,Reno,"Sandwiches, Food, Bakeries, Restaurants, Delis...",4.0,137,3.203944
150169,Oat Bakery,Santa Barbara,"Bakeries, Vegan, Specialty Food, Food Delivery...",5.0,123,3.201414
46027,20 Shekels Bread,Clearwater,"Bakeries, Coffee & Tea, Breakfast & Brunch, Or...",5.0,80,3.198504
28855,Native Bread,Indianapolis,"Food, Bakeries",4.5,21,3.197128
72290,Breadsmith,Oro Valley,"Food, Bakeries",4.5,52,3.196024
123119,Lost Bread Co.,Philadelphia,"Coffee & Tea, Food, Bakeries, Restaurants, Bre...",4.5,39,3.194281
84211,Beyond Bread,Tucson,"Bakeries, Sandwiches, Cafes, Restaurants, Food",4.5,439,3.190679
39742,Great Harvest Bread Company-Maplewood,Maplewood,"Restaurants, Food, Breakfast & Brunch, Bakerie...",4.5,27,3.190562