In [1]:
import sys
import os
sys.path.append(os.path.abspath(".."))

In [2]:
from retrieval.tfidf_search import TfidfSearchEngine

engine = TfidfSearchEngine(top_k=10)

In [3]:
engine.load_data("../data/processed/business_reviews_with_checkins.parquet")

✅ Loaded 150346 records with valid search_text.

In [4]:
engine.build_index()

✅ Loaded existing TF-IDF index from disk.

In [5]:
results = engine.search("best vegan pizza in Austin")

In [6]:
results

,name,city,categories,stars,review_count,tfidf_score
44273,Austin Lampson - Homeowners Financial Group,Santa Barbara,"Financial Advising, Mortgage Brokers, Home Ser...",5.0,16,0.461119
118169,Austin's Plumbing Service,Philadelphia,"Plumbing, Home Services, Water Heater Installa...",5.0,7,0.452320
29917,20th Street Pizza,Philadelphia,"Vegan, Restaurants, Pizza",4.5,78,0.442165
55497,Pizza Head,Saint Louis,"Vegetarian, Salad, Pizza, Vegan, Restaurants",4.5,188,0.434070
104179,Boardwalk Vegan,Havertown,"Pizza, Sandwiches, Restaurants, Vegan, Italian",5.0,37,0.398392
26488,Fino's Pizzeria & Restaurant,Philadelphia,"Restaurants, Pizza",3.0,55,0.378719
150290,Pizza Guru,Santa Barbara,"Restaurants, Pizza, Food",4.0,299,0.369499
110819,Hobo Coffee Shack,Glenside,"Restaurants, Gluten-Free, Vegetarian, Cheesest...",4.5,9,0.366080
109726,Americana Pizza,Boise,"Pizza, Vegan, Restaurants",4.5,50,0.362803
75673,Dough to Dough,New Orleans,"Donuts, Restaurants, Vegan, Food, Pizza",4.0,9,0.358643

In [7]:
engine.search("bread")

,name,city,categories,stars,review_count,tfidf_score
91676,Great Harvest Bread Co,Reno,"Restaurants, Food, Bakeries, American (New)",4.5,11,0.646759
137078,Barrio Bread,Tucson,"Food, Specialty Food, Bakeries, Restaurants",5.0,221,0.560555
29032,Bunny Bread Warehouse,Gretna,"Food, Restaurants, Bakeries",3.0,6,0.556785
143755,Cobs Bread,Edmonton,"Food, Bakeries",4.0,17,0.523107
72773,House of Bread,Reno,"Sandwiches, Food, Bakeries, Restaurants, Delis...",4.0,137,0.504712
28855,Native Bread,Indianapolis,"Food, Bakeries",4.5,21,0.494962
140661,Green Lion Breads,Phoenixville,"Bakeries, Food",5.0,5,0.493758
117274,Great Harvest Bread Co,Wayne,"Food, Bakeries, Restaurants",3.5,20,0.487235
72290,Breadsmith,Oro Valley,"Food, Bakeries",4.5,52,0.483344
39742,Great Harvest Bread Company-Maplewood,Maplewood,"Restaurants, Food, Breakfast & Brunch, Bakerie...",4.5,27,0.482059